/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebrtcTestRouteImport } from './routes/webrtc-test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MicrophoneTestRouteImport } from './routes/microphone-test'
import { Route as MediaTestRouteImport } from './routes/media-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CameraTestRouteImport } from './routes/camera-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'

const WebrtcTestRoute = WebrtcTestRouteImport.update({
  id: '/webrtc-test',
  path: '/webrtc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrophoneTestRoute = MicrophoneTestRouteImport.update({
  id: '/microphone-test',
  path: '/microphone-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaTestRoute = MediaTestRouteImport.update({
  id: '/media-test',
  path: '/media-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraTestRoute = CameraTestRouteImport.update({
  id: '/camera-test',
  path: '/camera-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera-test': typeof CameraTestRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/media-test': typeof MediaTestRoute
  '/microphone-test': typeof MicrophoneTestRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/webrtc-test': typeof WebrtcTestRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera-test': typeof CameraTestRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/media-test': typeof MediaTestRoute
  '/microphone-test': typeof MicrophoneTestRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/webrtc-test': typeof WebrtcTestRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera-test': typeof CameraTestRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/media-test': typeof MediaTestRoute
  '/microphone-test': typeof MicrophoneTestRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/webrtc-test': typeof WebrtcTestRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera-test'
    | '/dashboard'
    | '/login'
    | '/media-test'
    | '/microphone-test'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/webrtc-test'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera-test'
    | '/dashboard'
    | '/login'
    | '/media-test'
    | '/microphone-test'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/webrtc-test'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/camera-test'
    | '/dashboard'
    | '/login'
    | '/media-test'
    | '/microphone-test'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/webrtc-test'
    | '/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraTestRoute: typeof CameraTestRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MediaTestRoute: typeof MediaTestRoute
  MicrophoneTestRoute: typeof MicrophoneTestRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  WebrtcTestRoute: typeof WebrtcTestRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webrtc-test': {
      id: '/webrtc-test'
      path: '/webrtc-test'
      fullPath: '/webrtc-test'
      preLoaderRoute: typeof WebrtcTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microphone-test': {
      id: '/microphone-test'
      path: '/microphone-test'
      fullPath: '/microphone-test'
      preLoaderRoute: typeof MicrophoneTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-test': {
      id: '/media-test'
      path: '/media-test'
      fullPath: '/media-test'
      preLoaderRoute: typeof MediaTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-test': {
      id: '/camera-test'
      path: '/camera-test'
      fullPath: '/camera-test'
      preLoaderRoute: typeof CameraTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraTestRoute: CameraTestRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MediaTestRoute: MediaTestRoute,
  MicrophoneTestRoute: MicrophoneTestRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  WebrtcTestRoute: WebrtcTestRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
